-- AlterTable
ALTER TABLE "Book" ADD COLUMN     "soldAt" TIMESTAMP(3),
ALTER COLUMN "status" SET DEFAULT 'PUBLISHED';

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
